### ISSUE TITLE
BigInt do not work compatible with big-integer polyfill

### ISSUE THREAD

**Issue by MiDark** [mysto/node-fpe#2]
Hi, I tried to make the library compatible with the **browser** environment, and since BigInt only works on iOS14+, I used the **big-integer** library(<https://www.npmjs.com/package/big-integer>) as a polyfill.  

I modified the following in FF3Cipher.js to support running scripts:  

add require:  
`const BigInt = require("big-integer");`  
change line 45:  
`0n` => `BigInt(0)`  
change line 258&367:  
`let y = BigInt("0x" + s.tostring("hex"));` => `let y = BigInt(s.tostring("hex"), 16);`  

However, when the test script was executed, the actual result did not match the expected result.  

```shell
not ok 9 should be strictly equal
  ---
    operator: equal
    expected: '869304086633418279'
    actual:   '750918814058654607'
    at: Test.<anonymous> (/GitHub/node-fpe/test/FF3CipherTest.js:50:5)
    stack: |-
      Error: should be strictly equal
```

I tried to modify some other places, but the problem could not be solved. Could you please help to fix the problem?  

Thanks!

**Comment by bschoening** [comment]
Hi, I took a look at big-integer library.  This test doesn't even involve a large int, so its not clear why it would fail. 

The problem may be with the toString('hex').  Why did the args change?

**Comment by MiDark** [comment]
Thanks for your help!  

because big-Integer library doesn't allow BigInt to recognize strings starting with 0x as hexadecimal, and instead uses the second argument as base (somewhat similar to the convertToBigInt function in line 36), so I adjusted the argument here.  
 
Test hexadecimal conversion separately:  
```
const BigInteger = require("big-integer");  
const testHex="de7f3e4a210e3dff346924fbff750039";  
console.log(BigInt("0x"+testHex));  
// return 295749300147794922410226583415804985401n  
console.log(BigInteger(testHex,16));  
// return Integer { value: 295749300147794922410226583415804985401n }  
```

So they should have the same properties?

and I tried change `let y = BigInt("0x" + s.tostring("hex"));` to `let y = convertToBigInt(s.tostring("hex"), 16);` here, and it didn't pass the test either while using big-integer libiary.

**Comment by bschoening** [comment]
This is failing in the first encrypt operation using a NIST Test example.  You can find the original example with intermediate results in Sample #1 at https://csrc.nist.gov/csrc/media/projects/cryptographic-standards-and-guidelines/documents/examples/ff3samples.pdf.

If you restore the node-fpe console.log messages which are currently commented out, you will see the intermediate results and be able to determine where this is breaking.

Also, I've updated the unit test comments to a) clarify which are integration vs unit tests and b) fix the ordering of expected vs actual.

**Comment by MiDark** [comment]
Thank you, I have found the problem. 
The big-integer library will fall back to the range of int when running mathematics, resulting in a loss of accuracy. Just simply replace +, -, %, ** of BigInt with functions add, subtract, mod, pow, that would solve the problem.
