### ISSUE TITLE
Do you support custom character sets, which are consistent with java-fpe

### ISSUE THREAD

**Issue by 13517448203** [mysto/node-fpe#5]
SyntaxError: Cannot convert 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+/ to a BigInt

**Comment by bschoening** [comment]
Node's BigInt only supports radix values up to 36 (2^36) per the [2025 Language Spec](https://www.reddit.com/r/10s/comments/w63eet/when_and_where_to_move_on_from_hyper_hammer_53/).  Your example would require radix 10+26+26+2.

This is discussed in the [Implementation Notes](https://github.com/mysto/node-fpe?tab=readme-ov-file#implementation-notes):

> Therefore, this release supports a max base of 36, which can contain numeric digits 0-9 and lowercase alphabetic characters a-z.
